spring:
  datasource:
    url: jdbc:mysql://10.0.4.9:3306/aizip_app?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: wi33xc(^)m
  redis:
    host: redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.wieex: info